# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Runloop_FMDB' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Runloop_FMDB
  
  pod 'FMDB', '2.6.2'

end
